TRAIN:
  ENABLE: True
  DATASET: Ego4dLongTermAnticipation
  BATCH_SIZE: 256
DATA:
  NUM_FRAMES: 32
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  TASK: "long_term_anticipation"
FORECASTING:
  NUM_ACTIONS_TO_PREDICT: 4
  NUM_INPUT_CLIPS: 4
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 1e-4
  LR_POLICY: cosine_warmup
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  OPTIMIZING_METHOD: adam
  WEIGHT_DECAY: 1e-4
MODEL:
  NUM_CLASSES: [117, 521] #[117, 521]
  ARCH: slowfast
  MODEL_NAME: ActionRecognitionModel
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
  BERT_EMBEDS_PATH: '/cluster/project/cvg/students/azaera/noun_egovlp_distilbert_embs_cls'
TEST:
  ENABLE: True
  DATASET: Ego4dLongTermAnticipation
  BATCH_SIZE: 256
  EVAL_VAL: True
DATA_LOADER:
  NUM_WORKERS: 3
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: /cluster/project/cvg/students/azaera/ar_outputs/ #/cluster/scratch/azaera/ar_outputs/palm_ar_output_bert_self_att_ram_plus